import QueryProvider from "@/components/QueryProvider";
import "./globals.css";

export const metadata = {
  title: "Super simple CMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-gray-700 bg-gray-50">
        <header></header>
        <QueryProvider>{children}</QueryProvider>

        <footer></footer>
      </body>
    </html>
  );
}
