import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-gray-700 bg-gray-50">
        <header></header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
